///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class R {
  R._();

  static const String filesIndex = 'assets/files/index.html';
  static const String filesYz = 'assets/files/yz.json';
  static const String imagesErrorImage = 'assets/images/errorImage.png';
  static const String imagesHeaderIcon = 'assets/images/headerIcon.jpg';
  static const String imagesPlaceholder = 'assets/images/placeholder.gif';
  static const String imagesWhite = 'assets/images/white.jpeg';
  static const String jsonCategory = 'assets/json/category.json';
  static const String jsonI18n = 'assets/json/i18n.json';
  static const String jsonMeal = 'assets/json/meal.json';
  static const String tabbarGroup = 'assets/images/tabbar/group.png';
  static const String tabbarGroupActive = 'assets/images/tabbar/group_active.png';
  static const String tabbarHome = 'assets/images/tabbar/home.png';
  static const String tabbarHomeActive = 'assets/images/tabbar/home_active.png';
  static const String tabbarMall = 'assets/images/tabbar/mall.png';
  static const String tabbarMallActive = 'assets/images/tabbar/mall_active.png';
  static const String tabbarProfile = 'assets/images/tabbar/profile.png';
  static const String tabbarProfileActive = 'assets/images/tabbar/profile_active.png';
  static const String tabbarSubject = 'assets/images/tabbar/subject.png';
  static const String tabbarSubjectActive = 'assets/images/tabbar/subject_active.png';

}
